# Generated by Django 5.1.2 on 2025-10-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('entity_signature', models.CharField(db_index=True, max_length=512)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RawNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=128)),
                ('source_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('byline', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('fingerprint', models.CharField(max_length=256, unique=True)),
                ('language', models.CharField(default='en', max_length=16)),
                ('country_hint', models.CharField(blank=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('summary', models.CharField(max_length=500)),
                ('narrative', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='geopol.conflict')),
                ('sources', models.ManyToManyField(related_name='episodes', to='geopol.rawnews')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('conflict', 'date')},
            },
        ),
    ]
